VehicleRentalProject/Models/ViewModels/Rental/FinedUserViewModel.cs
namespace VehicleRentalProject.Web.Models.ViewModels.Rental
{
    public class FinedUserViewModel
    {
        public int RentalId { get; set; }
        public string VehicleNumber { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime? ReturnDate { get; set; }
        public decimal PenaltyAmount { get; set; }
        public string FullName { get; set; }
        public string UserName { get; set; }
    }
}

VehicleRentalProject/Models/ViewModels/Rental/RentalHistoryViewModel.cs
using VehicleRentalProject.Models;

namespace VehicleRentalProject.Web.Models.ViewModels.Rental
{
    public class RentalHistoryViewModel
    {
        public int RentalId { get; set; }
        public string VehicleNumber { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime? ReturnDate { get; set; }
        public int TotalPrice { get; set; }
        public string Status { get; set; }
        public int PenaltyAmount { get; set; }
        public ApplicationUser ApplicationUser { get; set; }
    }

}

VehicleRentalProject/Models/ViewModels/Rental/UpdateRentalStatusViewModel.cs
using VehicleRentalProject.Models;

namespace VehicleRentalProject.Web.Models.ViewModels.Rental
{
    public class UpdateRentalStatusViewModel
    {
        public int Id { get; set; }
        public string VehicleNumber { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime? ReturnDate { get; set; }
        public int TotalPrice { get; set; }
        public string Status { get; set; }
        public int PenaltyAmount { get; set; }
        public string ApplicationUser { get; set; }
    }
}

VehicleRentalProject/Areas/Admin/Controllers/RentalsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using VehicleRentalProject.Repositories.Infrastructure;
using AutoMapper;
using VehicleRentalProject.Web.Models.ViewModels.Rental;
using DinkToPdf.Contracts;
using DinkToPdf;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using System.IO;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Razor;
using Microsoft.AspNetCore.Mvc.Abstractions;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using VehicleRentalProject.Repositories.Implementation;
using iTextSharp.text.pdf;
using iTextSharp.text;



namespace VehicleRentalProject.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class RentalsController : Controller
    {
        private readonly IRentalRepository _rentalRepository;
        private readonly IMapper _mapper;
        private readonly IUserService _userService;

        public RentalsController(
            IRentalRepository rentalRepository,
            IMapper mapper
,
            IUserService userService)
        {
            _rentalRepository = rentalRepository;
            _mapper = mapper;
            _userService = userService;
        }

        public async Task<IActionResult> Index()
        {
            var rentals = await _rentalRepository.GetAllRentals();
            var rentalViewModels = _mapper.Map<List<RentalHistoryViewModel>>(rentals);

            return View(rentalViewModels);
        }

        [HttpGet]
        public async Task<IActionResult> UpdateStatus(int id)
        {
            var rental = await _rentalRepository.GetRentalById(id);
            var applicationUser = _userService.GetApplicationUser(rental.ApplicationUserId);
            var updateStatusViewModel = _mapper.Map<UpdateRentalStatusViewModel>(rental);
            return View(updateStatusViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateStatus(UpdateRentalStatusViewModel vm)
        {

            var rental = await _rentalRepository.GetRentalById(vm.Id);
            rental.RentalStatus = vm.Status;

            if (vm.PenaltyAmount > 0)
            {
                rental.PenaltyAmount = vm.PenaltyAmount;
            }
            await _rentalRepository.UpdateRental(rental);

            return RedirectToAction(nameof(Index));

        }

        public async Task<IActionResult> FinedUsersReport()
        {
            var finedRentals = await _rentalRepository.GetFinedRentalsAsync();
            var vm = finedRentals.Select(r => new FinedUserViewModel
            {
                RentalId = r.Id,
                VehicleNumber = r.Vehicle.VehicleNumber,
                StartDate = r.StartDate,
                ReturnDate = r.ReturnDate,
                PenaltyAmount = r.PenaltyAmount,
                FullName = r.ApplicationUser.FullName,
                UserName = r.ApplicationUser.UserName
            }).ToList();

            return View(vm);
        }

        public async Task<IActionResult> ExportFinedUsersReportToPDF()
        {
            var finedRentals = await _rentalRepository.GetFinedRentalsAsync();
            var vm = finedRentals.Select(r => new FinedUserViewModel
            {
                RentalId = r.Id,
                VehicleNumber = r.Vehicle.VehicleNumber,
                StartDate = r.StartDate,
                ReturnDate = r.ReturnDate,
                PenaltyAmount = r.PenaltyAmount,
                FullName = r.ApplicationUser.FullName,
                UserName = r.ApplicationUser.UserName
            }).ToList();

            using (var stream = new MemoryStream())
            {
                Document document = new Document();
                PdfWriter.GetInstance(document, stream).CloseStream = false;

                document.Open();
                document.Add(new Paragraph("Отчет о всех оштрафованных пользователях", GetRussianFont()));

                document.Add(new Paragraph("\n", GetRussianFont()));
                document.Add(new Paragraph("\n", GetRussianFont()));

                PdfPTable table = new PdfPTable(6);
                table.AddCell(new PdfPCell(new Phrase("Номер аренды", GetRussianFont())));
                table.AddCell(new PdfPCell(new Phrase("Номер автомобиля", GetRussianFont())));
                table.AddCell(new PdfPCell(new Phrase("Дата начала", GetRussianFont())));
                table.AddCell(new PdfPCell(new Phrase("Дата возврата", GetRussianFont())));
                table.AddCell(new PdfPCell(new Phrase("Штрафная сумма", GetRussianFont())));
                table.AddCell(new PdfPCell(new Phrase("Пользователь", GetRussianFont())));

                foreach (var rental in vm)
                {
                    table.AddCell(new PdfPCell(new Phrase(rental.RentalId.ToString(), GetRussianFont())));
                    table.AddCell(new PdfPCell(new Phrase(rental.VehicleNumber, GetRussianFont())));
                    table.AddCell(new PdfPCell(new Phrase(rental.StartDate.ToString("dd.MM.yyyy"), GetRussianFont())));
                    table.AddCell(new PdfPCell(new Phrase(rental.ReturnDate?.ToString("dd.MM.yyyy"), GetRussianFont())));
                    table.AddCell(new PdfPCell(new Phrase(rental.PenaltyAmount.ToString("C"), GetRussianFont())));
                    table.AddCell(new PdfPCell(new Phrase($"{rental.FullName} ({rental.UserName})", GetRussianFont())));
                }

                document.Add(table);
                document.Close();

                byte[] bytes = stream.ToArray();
                stream.Close();

                return File(bytes, "application/pdf", "FinedUsersReport.pdf");
            }
        }

        public async Task<IActionResult> GenerateRentalAgreement(int id)
        {
            var rental = await _rentalRepository.GetRentalById(id);
            var applicationUser = _userService.GetApplicationUser(rental.ApplicationUserId);

            using (var stream = new MemoryStream())
            {
                Document document = new Document();
                PdfWriter.GetInstance(document, stream).CloseStream = false;

                document.Open();
                document.Add(new Paragraph("Договор аренды транспортного средства", GetRussianFont()));

                document.Add(new Paragraph("\n", GetRussianFont()));
                document.Add(new Paragraph("\n", GetRussianFont()));

                PdfPTable table = new PdfPTable(2);
                table.WidthPercentage = 100;
                table.SetWidths(new float[] { 1, 2 });

                table.AddCell(new PdfPCell(new Phrase("Арендодатель:", GetRussianFont())));
                table.AddCell(new PdfPCell(new Phrase("             ", GetRussianFont())));

                document.Add(new Paragraph("\n\n", GetRussianFont()));

                table.AddCell(new PdfPCell(new Phrase("Арендатор:", GetRussianFont())));
                table.AddCell(new PdfPCell(new Phrase(applicationUser.FullName, GetRussianFont())));
                table.AddCell(new PdfPCell(new Phrase("Дата рождения:", GetRussianFont())));
                table.AddCell(new PdfPCell(new Phrase("              ", GetRussianFont())));
                table.AddCell(new PdfPCell(new Phrase("Адрес:", GetRussianFont())));
                table.AddCell(new PdfPCell(new Phrase(applicationUser.Address, GetRussianFont())));

                table.AddCell(new PdfPCell(new Phrase("Транспортное средство:", GetRussianFont())));
                table.AddCell(new PdfPCell(new Phrase(rental.Vehicle.VehicleNumber, GetRussianFont())));

                table.AddCell(new PdfPCell(new Phrase("Дата начала аренды:", GetRussianFont())));
                table.AddCell(new PdfPCell(new Phrase(rental.StartDate.ToString("dd.MM.yyyy"), GetRussianFont())));

                table.AddCell(new PdfPCell(new Phrase("Дата окончания аренды:", GetRussianFont())));
                table.AddCell(new PdfPCell(new Phrase(rental.ReturnDate?.ToString("dd.MM.yyyy"), GetRussianFont())));

                table.AddCell(new PdfPCell(new Phrase("Стоимость аренды:", GetRussianFont())));
                table.AddCell(new PdfPCell(new Phrase(rental.TotalPrice.ToString("C"), GetRussianFont())));

                document.Add(table);
                document.Add(new Paragraph("\n\n", GetRussianFont()));

                document.Add(new Paragraph("Договор аренды транспортного средства", GetRussianFont()));
                document.Add(new Paragraph("1.1. Предметом настоящего договора является транспортное средство, далее ТС:", GetRussianFont()));
                document.Add(new Paragraph($"Марка, модель {rental.Vehicle.VehicleName} {rental.Vehicle.VehicleModel}", GetRussianFont()));
                document.Add(new Paragraph($"Тип транспортного средства по ПТС {rental.Vehicle.VehicleType}", GetRussianFont()));
                document.Add(new Paragraph($"Цвет {rental.Vehicle.VehicleColor}", GetRussianFont()));
                document.Add(new Paragraph("1.2. Указанное ТС принадлежит Арендодателю на основании паспорта транспортного средства.", GetRussianFont()));
                document.Add(new Paragraph("2.1. Арендодатель обязуется:", GetRussianFont()));
                document.Add(new Paragraph("2.1.1. Передать ТС Арендатору не позднее дня, следующего за днем подписания настоящего договора;", GetRussianFont()));
                document.Add(new Paragraph("2.1.2. Представить Арендатору транспортное средство в исправном техническом состоянии, без дефектов;", GetRussianFont()));
                document.Add(new Paragraph("2.1.3. Передать Арендатору технический паспорт транспортного средства и ключи от данного транспортного средства;", GetRussianFont()));
                document.Add(new Paragraph("2.1.4. Производить страхование транспортного средства за свой счет.", GetRussianFont()));

VehicleRentalProject/Areas/Admin/Views/Rentals/FinedUsersReport.cshtml
@model IEnumerable<VehicleRentalProject.Web.Models.ViewModels.Rental.FinedUserViewModel>

@{
    var culture = new System.Globalization.CultureInfo("be-BY");
    ViewData["Title"] = "Отчет о всех оштрафованных пользователях";
}

<h2>Отчет о всех оштрафованных пользователях</h2>

<table class="table">
    <thead>
        <tr>
            <th>Номер аренды</th>
            <th>Номер автомобиля</th>
            <th>Дата начала</th>
            <th>Дата возврата</th>
            <th>Штрафная сумма</th>
            <th>Пользователь</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var rental in Model)
        {
            <tr>
                <td>@rental.RentalId</td>
                <td>@rental.VehicleNumber</td>
                <td>@rental.StartDate.ToString("dd.MM.yyyy")</td>
                <td>@rental.ReturnDate?.ToString("dd.MM.yyyy")</td>
                <td>@rental.PenaltyAmount.ToString("C", culture)</td>
                <td>@rental.UserName (@rental.FullName)</td>
            </tr>
        }
    </tbody>
</table>

<a asp-action="ExportFinedUsersReportToPDF" class="btn btn-primary">Экспорт в PDF</a>

<style>
    th {
        background-color: #f8f9fa;
        color: #343a40;
        font-weight: bold;
        text-align: left;
    }
</style>

VehicleRentalProject/Areas/Admin/Views/Rentals/Index.cshtml
@model IEnumerable<VehicleRentalProject.Web.Models.ViewModels.Rental.RentalHistoryViewModel>
@{
    var culture = new System.Globalization.CultureInfo("be-BY");
    ViewData["Title"] = "Все заявки на аренду";
}

<h2>Все заявки на аренду</h2>

<div class="mb-3">
    <a asp-area="Admin" asp-controller="Rentals" asp-action="FinedUsersReport" class="btn btn-info">Отчет о всех оштрафованных пользователях</a>
</div>

<table class="table">
    <thead>
        <tr>
            <th>Номер автомобиля</th>
            <th>Дата начала</th>
            <th>Дата возврата</th>
            <th>Штрафная сумма</th>
            <th>Сумма аренды</th>
            <th>Клиент</th>
            <th>Статус</th>
            <th>Действие</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var rental in Model)
        {
            <tr>
                <td>@rental.VehicleNumber</td>
                <td>@rental.StartDate.ToString("dd.MM.yyyy")</td>
                <td>@rental.ReturnDate?.ToString("dd.MM.yyyy")</td>
                <td>@rental.PenaltyAmount.ToString("C", culture)</td>
                <td>@rental.TotalPrice.ToString("C", culture)</td>
                <td>@(rental.ApplicationUser != null ? rental.ApplicationUser.UserName : "Неизвестный пользователь")</td>
                <td>@rental.Status</td>
                <td>
                    <a asp-action="UpdateStatus" asp-route-id="@rental.RentalId" class="btn btn-primary">Изменить статус</a>
                    @if (rental.Status == "Одобрено")
                    {
                        <a asp-action="GenerateRentalAgreement" asp-route-id="@rental.RentalId" class="btn btn-success">Создать отчет</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

VehicleRentalProject/Areas/Admin/Views/Rentals/UpdateStatus.cshtml
@model VehicleRentalProject.Web.Models.ViewModels.Rental.UpdateRentalStatusViewModel

@{
    ViewData["Title"] = "Изменить статус заявки";
}

<h2>Изменить статус заявки</h2>
<form asp-action="UpdateStatus" enctype="multipart/form-data">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label>Клиент</label>
        <input type="text" class="form-control" value="@Model.ApplicationUser" readonly />
    </div>
    <div class="form-group">
        <label>Номер автомобиля</label>
        <input type="text" class="form-control" value="@Model.VehicleNumber" readonly />
    </div>
    <div class="form-group">
        <label>Дата начала</label>
        <input type="text" class="form-control" value="@Model.StartDate.ToString("dd.MM.yyyy")" readonly />
    </div>
    <div class="form-group">
        <label>Дата возврата</label>
        <input type="text" class="form-control" value="@Model.ReturnDate?.ToString("dd.MM.yyyy")" readonly />
    </div>
    <div class="form-group">
        <label>Штрафная сумма</label>
        <input type="text" asp-for="PenaltyAmount" class="form-control" />
    </div>
    <div class="form-group">
        <label>Общая цена</label>
        <input type="text" class="form-control" value="@Model.TotalPrice" readonly />
    </div>

    <div class="form-group">
        <label>Статус</label>
        <select asp-for="Status" class="form-control">
            <option value="На рассмотрении">На рассмотрении</option>
            <option value="Одобрено">Одобрено</option>
            <option value="Не одобрено">Не одобрено</option>
        </select>
    </div>

    <button type="submit" class="btn btn-primary">Сохранить изменения</button>
</form>