VehicleRentalProject/Models/ViewModels/Vehicle/CreateVehicleViewModel.cs
namespace VehicleRentalProject.Models.ViewModels.Vehicle
{
    public class CreateVehicleViewModel
    {
        public string VehicleName { get; set; }
        public string VehicleType { get; set; }
        public string VehicleModel { get; set; }
        public string VehicleNumber { get; set; }
        public string VehicleColor { get; set; }
        public string VehicleDescription { get; set; }
        public int DailyRate { get; set; }
        //public string VehicleImage { get; set; }
        public IFormFile VehicleImageUrl { get; set; }
        public int VehiclePrice { get; set; }
        public bool IsAvailable { get; set; } = true;
        public bool IsDeleted { get; set; } = false;
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
        public DateTime? UpdatedAt { get; set; } = DateTime.UtcNow;
    }
}

VehicleRentalProject/Models/ViewModels/Vehicle/EditVehicleViewModel.cs
namespace VehicleRentalProject.Web.Models.ViewModels.Vehicle
{
    public class EditVehicleViewModel
    {
        public int Id { get; set; }
        public string VehicleName { get; set; }
        public string VehicleType { get; set; }
        public string VehicleModel { get; set; }
        public string VehicleNumber { get; set; }
        public string VehicleColor { get; set; }
        public string VehicleDescription { get; set; }
        public IFormFile VehicleImageUrl { get; set; }
        public int DailyRate { get; set; }
        public int VehiclePrice { get; set; }
        public bool IsAvailable { get; set; } = true;
        public bool IsDeleted { get; set; } = false;
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
        public DateTime? UpdatedAt { get; set; }
    }
}

VehicleRentalProject/Models/ViewModels/Vehicle/ListVehicleViewModel.cs
using System.Collections;
using VehicleRentalProject.Utility;

namespace VehicleRentalProject.Models.ViewModels.Vehicle
{
    public class ListVehicleViewModel
    {
        public IEnumerable<VehicleViewModel> VehicleList { get; set; }
        public PageInfo PageInfo { get; set; }
        public string SearchingText { get; set; }
    }
}

VehicleRentalProject/Models/ViewModels/Vehicle/SummaryViewModel.cs
using System.ComponentModel.DataAnnotations;
using VehicleRentalProject.Models;
using VehicleRentalProject.Web.Validations;

namespace VehicleRentalProject.Web.Models.ViewModels.Vehicle
{
    public class SummaryViewModel
    {
        [Required]
        public string VehicleType { get; set; }

        [Required]
        public DateTime StartDate { get; set; }

        [Required]
        public DateTime? EndDate { get; set; }

        [Required]
        public string VehicleNumber { get; set; }

        [Required]
        [Range(1, double.MaxValue, ErrorMessage = "Общая сумма должна быть положительным числом.")]
        public int TotalAmount { get; set; }

        public int TotalDuration { get; set; }
        public string VehicleImage { get; set; }

        [Required]
        public int Id { get; set; }

        public ApplicationUser ApplicationUser { get; set; }
    }

}

VehicleRentalProject/Models/ViewModels/Vehicle/VehicleDetailsViewModel.cs
using System.ComponentModel.DataAnnotations;
using VehicleRentalProject.Web.Validations;

namespace VehicleRentalProject.Web.Models.ViewModels.Vehicle
{
    public class VehicleDetailsViewModel
    {
        public int Id { get; set; }
        public string VehicleName { get; set; }
        public string VehicleType { get; set; }
        public string VehicleModel { get; set; }
        public string VehicleNumber { get; set; }
        public string VehicleColor { get; set; }
        public string VehicleDescription { get; set; }
        public string VehicleImage { get; set; }
        public int DailyRate { get; set; }

        [Display(Name ="Start Date")]
        [Required(ErrorMessage ="Пожалуйста выберите дату.")]
        [DataType(DataType.Date)]
        public DateTime StartDate { get; set; }

        [Display(Name = "End Date")]
        [Required(ErrorMessage = "Пожалуйста выберите Конечную дату.")]
        [DataType(DataType.Date)]
        [CustomDateRange(ErrorMessage = "Дата окончания должна быть больше или равна дате начала")]
        public DateTime? EndDate { get; set; }

        public int TotalAmount { get; set; }
    }
}

VehicleRentalProject/Models/ViewModels/Vehicle/VehicleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace VehicleRentalProject.Models.ViewModels.Vehicle
{
    public class VehicleViewModel
    {
        public int Id { get; set; }
        public string VehicleName { get; set; }
        public string VehicleType { get; set; }
        public string VehicleModel { get; set; }
        public string VehicleNumber { get; set; }
        public string VehicleColor { get; set; }
        public string VehicleDescription { get; set; }
        public string VehicleImage { get; set; }
        public int DailyRate { get; set; }
        public int VehiclePrice { get; set; }
        public bool IsAvailable { get; set; } = true;
        public bool IsDeleted { get; set; } = false;
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
        public DateTime? UpdatedAt { get; set; }

    }
}

VehicleRentalProject/Areas/Admin/Controllers/VehiclesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using VehicleRentalProject.Models;
using VehicleRentalProject.Models.ViewModels.Vehicle;
using VehicleRentalProject.Repositories.Infrastructure;
using VehicleRentalProject.Utility;
using VehicleRentalProject.Web.Models.ViewModels.Rental;
using VehicleRentalProject.Web.Models.ViewModels.Vehicle;

namespace VehicleRentalProject.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class VehiclesController : Controller
    {
        private readonly IVehicleRepository _vehicleRepository;
        private IMapper _mapper;

        public VehiclesController(IVehicleRepository vehicleRepository, IMapper mapper)
        {
            _vehicleRepository = vehicleRepository;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index(int pageNumber = 1, int pageSize = 10, string searchingText = null)
        {
            var vehicles = _vehicleRepository.GetVehicles().GetAwaiter().GetResult();

            if (!string.IsNullOrEmpty(searchingText))
            {
                vehicles = vehicles.Where(v => v.VehicleNumber.Contains(searchingText));
            }

            var totalItems = vehicles.Count();

            var paginatedVehicles = vehicles.Skip((pageNumber - 1) * pageSize).Take(pageSize);
            var viewModelList = _mapper.Map<List<VehicleViewModel>>(paginatedVehicles);

            var vehicleViewModel = new ListVehicleViewModel
            {
                VehicleList = viewModelList,
                PageInfo = new PageInfo
                {
                    ItemsPerPage = pageSize,
                    CurrentPage = pageNumber,
                    TotalItems = totalItems
                }
            };

            return View(vehicleViewModel);
        }

        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateVehicleViewModel vm)
        {
            var model = _mapper.Map<Vehicle>(vm);
            await _vehicleRepository.InsertVehicle(model);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var vehicle = await _vehicleRepository.GetVehicleById(id);
            var vehicleViewModel = _mapper.Map<EditVehicleViewModel>(vehicle);
            return View(vehicleViewModel);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(EditVehicleViewModel vm)
        {
            var vehicle = _mapper.Map<Vehicle>(vm);
            await _vehicleRepository.UpdateVehicle(vehicle);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var vehicle = await _vehicleRepository.GetVehicleById(id);
            await _vehicleRepository.DeleteVehicle(vehicle.Id);
            return RedirectToAction("Index");
        }

    }
}

VehicleRentalProject/Areas/Admin/Views/Vehicles/Create.cshtml
@using VehicleRentalProject.Models.ViewModels.Vehicle
@model CreateVehicleViewModel
@{
    ViewData["Title"] = "Добавление машины";
}

<div class="container">
    <h2>Добавить новую машину</h2>
    <hr />

    <form asp-action="Create" asp-controller="Vehicles" enctype="multipart/form-data">
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <label for="VehicleName">Название машины:</label>
                    <input type="text" class="form-control" id="VehicleName" name="VehicleName" required />
                </div>

                <div class="form-group">
                    <label for="VehicleType">Тип машины:</label>
                    <select name="VehicleType" class="form-control" id="VehicleType" required>
                        <option value="">Выберите тип</option>
                        <option value="Седан">Седан</option>
                        <option value="Седан">Купе</option>
                        <option value="Седан">Универсал</option>
                        <option value="Хэтчбек">Хэтчбек</option>
                        <option value="Седан">Внедорожник</option>
                        <option value="Кроссовер">Кроссовер</option>
                        <option value="Седан">Пикап</option>
                        <option value="Минивэн">Минивэн</option>
                    </select>
                </div>


                <div class="form-group">
                    <label for="VehicleModel">Модель машины:</label>
                    <input type="text" class="form-control" id="VehicleModel" name="VehicleModel" required />
                </div>
            </div>


            <div class="col-md-4">
                <div class="form-group">
                    <label for="VehicleNumber">Номер машины:</label>
                    <input type="text" class="form-control" id="VehicleNumber" name="VehicleNumber" required/>
                    <small class="form-text text-muted">Формат номера: АА1234BB1 или A1234BB12</small>
                </div>

                <div class="form-group">
                    <label for="VehicleColor">Цвет машины:</label>
                    <input type="text" class="form-control" id="VehicleColor" name="VehicleColor" required />
                </div>

                <div class="form-group">
                    <label for="VehicleDescription">Дополнительная информация:</label>
                    <textarea class="form-control" id="VehicleDescription" name="VehicleDescription" rows="3" required></textarea>
                </div>
            </div>

            <div class="col-md-4">
                <div class="form-group">
                    <label for="VehicleImage">Изображение машины:</label>
                    <input type="file" class="form-control-file" id="VehicleImageUrl" name="VehicleImageUrl" required />
                </div>

                <div class="form-group">
                    <label for="VehiclePrice">Цена машины:</label>
                    <input type="number" class="form-control" id="VehiclePrice" name="VehiclePrice" required />
                </div>

                <div class="form-group">
                    <label for="DailyRate">Дневная Ставка:</label>
                    <input type="number" class="form-control" id="DailyRate" name="DailyRate" required />
                </div>

                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="IsAvailable" name="IsAvailable" />
                    <label class="form-check-label" for="IsAvailable">Доступность</label>
                </div>
            </div>
        </div>

        <br />

        <div class="text-center">

            <button type="submit" class="btn btn-primary">Добавить</button>
            <a asp-action="Index" asp-controller="Vehicles" class="btn btn-secondary">Вернуться</a>
        </div>
    </form>
</div>

VehicleRentalProject/Areas/Admin/Views/Vehicles/Edit.cshtml
@using VehicleRentalProject.Web.Models.ViewModels.Vehicle;
@model EditVehicleViewModel
@{
    ViewData["Title"] = "Редактирование машины";
}

<div class="container">
    <h2>Добавить новую машину</h2>
    <hr />

    <form asp-action="Edit" asp-controller="Vehicles" enctype="multipart/form-data">
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <input type="hidden" asp-for="Id" name="Id" />
                    <label for="VehicleName">Название машины:</label>
                    <input type="text" class="form-control" asp-for="VehicleName" required />
                </div>

                <div class="form-group">
                    <label for="VehicleType">Тип машины:</label>
                    <select name="VehicleType" class="form-control" id="VehicleType" required>
                        <option value="">Выберите тип</option>
                        <option value="Седан">Седан</option>
                        <option value="Седан">Купе</option>
                        <option value="Седан">Универсал</option>
                        <option value="Хэтчбек">Хэтчбек</option>
                        <option value="Седан">Внедорожник</option>
                        <option value="Кроссовер">Кроссовер</option>
                        <option value="Седан">Пикап</option>
                        <option value="Минивэн">Минивэн</option>
                    </select>
                </div>

                <div class="form-group">
                    <label for="VehicleModel">Модель машины:</label>
                    <input type="text" class="form-control" asp-for="VehicleModel" required />
                </div>
            </div>


            <div class="col-md-4">
                <div class="form-group">
                    <label for="VehicleNumber">Номер машины:</label>
                    <input type="text" class="form-control" id="VehicleNumber" name="VehicleNumber" required pattern="^[АВЕКМНОРСТХ]{1,2}\d{3,4}[АВЕКМНОРСТХ]{2}\d{1,2}$" title="Введите корректный номер машины" />
                    <small class="form-text text-muted">Формат номера: АА1234BB1 или A1234BB12</small>
                </div>

                <div class="form-group">
                    <label for="VehicleColor">Цвет машины:</label>
                    <input type="text" class="form-control" asp-for="VehicleColor" required />
                </div>

                <div class="form-group">
                    <label for="VehicleDescription">Дополнительная информация:</label>
                    <textarea class="form-control" asp-for="VehicleDescription" rows="3" required></textarea>
                </div>
            </div>

            <div class="col-md-4">
                <div class="form-group">
                    <label for="VehicleImage">Изображение машины:</label>
                    <input type="file" class="form-control-file" id="VehicleImageUrl" name="VehicleImageUrl" />
                </div>

                <div class="form-group">
                    <label for="VehiclePrice">Цена машины:</label>
                    <input type="number" class="form-control" asp-for="VehiclePrice" required />
                </div>

                <div class="form-group">
                    <label for="DailyRate">Дневная Ставка:</label>
                    <input class="form-control" asp-for="DailyRate" required />
                </div>

                <div class="form-check">
                    <input type="checkbox" class="form-check-input" asp-for="IsAvailable" />
                    <label class="form-check-label" for="IsAvailable">Доступность</label>
                </div>
            </div>
        </div>

        <br />

        <div class="text-center">
            <button type="submit" class="btn btn-primary">Редактировать</button>
            <a asp-action="Index" asp-controller="Vehicles" class="btn btn-secondary">Вернуться</a>
        </div>

    </form>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script>
        function validateVehicleNumber() {
            const vehicleNumber = document.getElementById('VehicleNumber').value;
            const pattern = /^[АВЕКМНОРСТХ]{1,2}\d{3,4}[АВЕКМНОРСТХ]{2}\d{1,2}$/;
            if (!pattern.test(vehicleNumber)) {
                alert('Введите корректный номер машины.');
                return false;
            }
            return true;
        }
    </script>
}

VehicleRentalProject/Areas/Admin/Views/Vehicles/Index.cshtml
@using VehicleRentalProject.Models.ViewModels.Vehicle
@model ListVehicleViewModel

@{
    ViewData["Title"] = "Список машин";
}

<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Домашняя страница</a></li>
            <li class="breadcrumb-item active" aria-current="page">Список машин</li>
        </ol>
    </nav>

    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Список машин</h5>
            <h5 class="card-title"><a asp-action="Create" class="btn btn-success">Добавить новую машину</a></h5>
            <form method="get" action="">
                <div class="input-group mb-3">
                    <input type="text" class="form-control" name="searchingText" placeholder="Поиск..." />
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="submit" id="buttonSubmit">Найти</button>
                    </div>
                </div>
            </form>

            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Название</th>
                        <th>Тип</th>
                        <th>Модель</th>
                        <th>Номер</th>
                        <th>Цвет</th>
                        <th>Описание</th>
                        <th>Изображение</th>
                        <th></th>

                    </tr>
                </thead>
                <tbody>
                    @if (Model.VehicleList.Any())
                    {
                        foreach (var vehicle in Model.VehicleList)
                        {
                            <tr>
                                <td>@vehicle.Id</td>
                                <td>@vehicle.VehicleName</td>
                                <td>@vehicle.VehicleType</td>
                                <td>@vehicle.VehicleModel</td>
                                <td>@vehicle.VehicleNumber</td>
                                <td>@vehicle.VehicleColor</td>
                                <td>@vehicle.VehicleDescription</td>
                                <td><img src="@vehicle.VehicleImage" width="100" height="80" /></td>
                                <td>
                                    <a class="btn btn-primary" asp-action="Edit" asp-route-Id="@vehicle.Id">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                                            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z" />
                                        </svg>
                                    </a>
                                    <a class="btn btn-danger" asp-action="Delete" asp-route-Id="@vehicle.Id">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                                            <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5m-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5M4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06m6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528M8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5" />
                                        </svg>
                                    </a>
                                </td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="11" class="text-center">Машины не найдены.</td>
                        </tr>
                    }
                </tbody>
            </table>

            @if (Model.PageInfo.TotalPages > 1)
            {
                <nav aria-label="Страница навигации">
                    <ul class="pagination">
                        @if (Model.PageInfo.HasPreviousPage)
                        {
                            <li class="page-item"><a class="page-link" href="?pageNumber=@(Model.PageInfo.CurrentPage - 1)">Предыдущая</a></li>
                        }
                        @for (int i = 1; i <= Model.PageInfo.TotalPages; i++)
                        {
                            <li class="page-item @(Model.PageInfo.CurrentPage == i ? "active" : "")"><a class="page-link" href="?pageNumber=@i">@i</a></li>
                        }
                        @if (Model.PageInfo.HasNextPage)
                        {
                            <li class="page-item"><a class="page-link" href="?pageNumber=@(Model.PageInfo.CurrentPage + 1)">Следующая</a></li>
                        }
                    </ul>
                </nav>
            }
        </div>
    </div>
</div>